import path from "node:path";

import {
  compile,
  getCssCompiler,
  getErrors,
  getWarnings,
  readAsset,
} from "./helpers/index";

describe("built-in CSS support of webpack", () => {
  it("should work", async () => {
    const compiler = getCssCompiler("./builtin-css/index.js", {
      postcssOptions: {
        plugins: ["postcss-nested"],
      },
    });
    const stats = await compile(compiler);

    expect(readAsset("main.css", compiler, stats)).toMatchSnapshot("css");
    expect(getWarnings(stats)).toMatchSnapshot("warnings");
    expect(getErrors(stats)).toMatchSnapshot("errors");
  });

  it("should work with CSS modules", async () => {
    const compiler = getCssCompiler("./builtin-css/modules.js", {
      postcssOptions: {
        plugins: ["postcss-nested"],
      },
    });
    const stats = await compile(compiler);
    const css = readAsset("main.css", compiler, stats);

    // The class name is generated by webpack, only check that it was renamed
    expect(css).not.toContain(".link {");
    expect(css).toContain("color: black");
    expect(css).toContain("color: red");
    expect(getWarnings(stats)).toMatchSnapshot("warnings");
    expect(getErrors(stats)).toMatchSnapshot("errors");
  });

  it("should work with SugarSS", async () => {
    const compiler = getCssCompiler("./builtin-css/sss.js", {
      postcssOptions: {
        parser: "sugarss",
        hideNothingWarning: true,
      },
    });
    const stats = await compile(compiler);

    expect(readAsset("main.css", compiler, stats)).toMatchSnapshot("css");
    expect(getWarnings(stats)).toMatchSnapshot("warnings");
    expect(getErrors(stats)).toMatchSnapshot("errors");
  });

  it('should work with the "execute" option and CSS-in-JS', async () => {
    const compiler = getCssCompiler(
      "./builtin-css/jss.js",
      {},
      {
        module: {
          rules: [
            {
              test: /style\.js$/i,
              type: "css/auto",
              use: [
                {
                  loader: path.resolve(__dirname, "../src"),
                  options: {
                    postcssOptions: {
                      parser: "postcss-js",
                    },
                    execute: true,
                  },
                },
              ],
            },
          ],
        },
      },
    );
    const stats = await compile(compiler);

    expect(readAsset("main.css", compiler, stats)).toMatchSnapshot("css");
    expect(getWarnings(stats)).toMatchSnapshot("warnings");
    expect(getErrors(stats)).toMatchSnapshot("errors");
  });

  it("should generate source maps", async () => {
    const compiler = getCssCompiler(
      "./builtin-css/index.js",
      {
        sourceMap: true,
        postcssOptions: {
          plugins: ["postcss-nested"],
        },
      },
      {
        devtool: "source-map",
      },
    );
    const stats = await compile(compiler);
    const sourceMap = JSON.parse(readAsset("main.css.map", compiler, stats));

    expect(
      sourceMap.sources.some((source) => source.endsWith("css/style.css")),
    ).toBe(true);
    expect(getWarnings(stats)).toMatchSnapshot("warnings");
    expect(getErrors(stats)).toMatchSnapshot("errors");
  });

  it("should emit an error on invalid syntax", async () => {
    const compiler = getCssCompiler("./builtin-css/index.js", {
      postcssOptions: {
        hideNothingWarning: true,
        parser: "sugarss",
      },
    });
    const stats = await compile(compiler);

    expect(getWarnings(stats)).toMatchSnapshot("warnings");
    expect(getErrors(stats)).toMatchSnapshot("errors");
  });
});
